version: '3.8'

services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hotels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=
      - SMTP_HOST=
      - SMTP_PORT=465
      - SMTP_USER=
      - SMTP_PASSWORD=
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    command: npm rin dev
    volumes:
      - ./frontend:/my-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: